// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/domain/order_domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VendorId      int64                  `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Product       *OrderProduct          `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      uint32                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    string                 `protobuf:"bytes,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Comment       string                 `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_v1_domain_order_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_order_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_v1_domain_order_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetProduct() *OrderProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Order) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *Order) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProduct) Reset() {
	*x = OrderProduct{}
	mi := &file_v1_domain_order_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProduct) ProtoMessage() {}

func (x *OrderProduct) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_order_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProduct.ProtoReflect.Descriptor instead.
func (*OrderProduct) Descriptor() ([]byte, []int) {
	return file_v1_domain_order_domain_proto_rawDescGZIP(), []int{1}
}

func (x *OrderProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderProduct) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Delivery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           int64                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 1- delivery to pick up point 2 - delivery to client address
	PickUpPointId  *int64                 `protobuf:"varint,2,opt,name=pick_up_point_id,json=pickUpPointId,proto3,oneof" json:"pick_up_point_id,omitempty"`
	ClintAddressId *int64                 `protobuf:"varint,3,opt,name=clint_address_id,json=clintAddressId,proto3,oneof" json:"clint_address_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_v1_domain_order_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_order_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_v1_domain_order_domain_proto_rawDescGZIP(), []int{2}
}

func (x *Delivery) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Delivery) GetPickUpPointId() int64 {
	if x != nil && x.PickUpPointId != nil {
		return *x.PickUpPointId
	}
	return 0
}

func (x *Delivery) GetClintAddressId() int64 {
	if x != nil && x.ClintAddressId != nil {
		return *x.ClintAddressId
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int64                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 1 - in pick up point by cash,  2 - in pick up point by card, 3 - online by card, 4 online by crypto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_v1_domain_order_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_order_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_v1_domain_order_domain_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_v1_domain_order_domain_proto protoreflect.FileDescriptor

const file_v1_domain_order_domain_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/domain/order_domain.proto\x128github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\x03R\bvendorId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12`\n" +
	"\aproduct\x18\x05 \x01(\v2F.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderProductR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\rR\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\a \x01(\tR\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\tR\n" +
	"totalPrice\x12\x18\n" +
	"\acomment\x18\t \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"m\n" +
	"\fOrderProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"\xa5\x01\n" +
	"\bDelivery\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x12,\n" +
	"\x10pick_up_point_id\x18\x02 \x01(\x03H\x00R\rpickUpPointId\x88\x01\x01\x12-\n" +
	"\x10clint_address_id\x18\x03 \x01(\x03H\x01R\x0eclintAddressId\x88\x01\x01B\x13\n" +
	"\x11_pick_up_point_idB\x13\n" +
	"\x11_clint_address_id\"\x1d\n" +
	"\aPayment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04typeBAZ?github.com/martketplace-vkr/order/pkg/api/grpc/v1/domain;domainb\x06proto3"

var (
	file_v1_domain_order_domain_proto_rawDescOnce sync.Once
	file_v1_domain_order_domain_proto_rawDescData []byte
)

func file_v1_domain_order_domain_proto_rawDescGZIP() []byte {
	file_v1_domain_order_domain_proto_rawDescOnce.Do(func() {
		file_v1_domain_order_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_domain_order_domain_proto_rawDesc), len(file_v1_domain_order_domain_proto_rawDesc)))
	})
	return file_v1_domain_order_domain_proto_rawDescData
}

var file_v1_domain_order_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_domain_order_domain_proto_goTypes = []any{
	(*Order)(nil),                 // 0: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
	(*OrderProduct)(nil),          // 1: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderProduct
	(*Delivery)(nil),              // 2: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Delivery
	(*Payment)(nil),               // 3: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Payment
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_v1_domain_order_domain_proto_depIdxs = []int32{
	1, // 0: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order.product:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderProduct
	4, // 1: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_domain_order_domain_proto_init() }
func file_v1_domain_order_domain_proto_init() {
	if File_v1_domain_order_domain_proto != nil {
		return
	}
	file_v1_domain_order_domain_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_domain_order_domain_proto_rawDesc), len(file_v1_domain_order_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_domain_order_domain_proto_goTypes,
		DependencyIndexes: file_v1_domain_order_domain_proto_depIdxs,
		MessageInfos:      file_v1_domain_order_domain_proto_msgTypes,
	}.Build()
	File_v1_domain_order_domain_proto = out.File
	file_v1_domain_order_domain_proto_goTypes = nil
	file_v1_domain_order_domain_proto_depIdxs = nil
}
