syntax = "proto3";

package github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/martketplace-vkr/order/pkg/api/grpc/v1/domain;domain";

message Order {
  int64 id = 1;
  int64 user_id = 2;
  int64 vendor_id = 3;
  // Deprecated: use fulfillment_status.
  string status = 4;
  OrderProduct product = 5;
  uint32 quantity = 6;
  string unit_price = 7;
  string total_price = 8;
  string comment = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  string payment_status = 12;
  string fulfillment_status = 13;
  int64 delivery_address_id = 14;
  int64 currency_id = 15;
}

message OrderProduct {
  int64 product_id = 1;
  string product_name = 2;
  string image_url = 3;
}


message Delivery {
  int64 type = 1; // 1- delivery to pick up point 2 - delivery to client address
  optional int64 pick_up_point_id  = 2;
  optional int64 clint_address_id = 3;
}

message Payment{
  int64 type = 1; // 1 - in pick up point by cash,  2 - in pick up point by card, 3 - online by card, 4 online by crypto 
  int64 currency_id = 2;
}
