// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/order_client_service.proto

package client

import (
	domain "github.com/martketplace-vkr/order/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId          string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	ProductIds          []int64                `protobuf:"varint,3,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	ExpectedCartVersion uint64                 `protobuf:"varint,4,opt,name=expected_cart_version,json=expectedCartVersion,proto3" json:"expected_cart_version,omitempty"`
	Delivery            *domain.Delivery       `protobuf:"bytes,5,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Payment             *domain.Payment        `protobuf:"bytes,6,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *CheckoutRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *CheckoutRequest) GetExpectedCartVersion() uint64 {
	if x != nil {
		return x.ExpectedCartVersion
	}
	return 0
}

func (x *CheckoutRequest) GetDelivery() *domain.Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *CheckoutRequest) GetPayment() *domain.Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*domain.Order        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutResponse) GetOrders() []*domain.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *domain.Order          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderResponse) GetOrder() *domain.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListRequest) Reset() {
	*x = GetOrderListRequest{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListRequest) ProtoMessage() {}

func (x *GetOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListRequest.ProtoReflect.Descriptor instead.
func (*GetOrderListRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*domain.Order        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListResponse) Reset() {
	*x = GetOrderListResponse{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListResponse) ProtoMessage() {}

func (x *GetOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListResponse.ProtoReflect.Descriptor instead.
func (*GetOrderListResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderListResponse) GetOrders() []*domain.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *domain.Order          `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderResponse) GetOrder() *domain.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type HasSuccessfulProductOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSuccessfulProductOrderRequest) Reset() {
	*x = HasSuccessfulProductOrderRequest{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSuccessfulProductOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSuccessfulProductOrderRequest) ProtoMessage() {}

func (x *HasSuccessfulProductOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSuccessfulProductOrderRequest.ProtoReflect.Descriptor instead.
func (*HasSuccessfulProductOrderRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{8}
}

func (x *HasSuccessfulProductOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HasSuccessfulProductOrderRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type HasSuccessfulProductOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasOrder      bool                   `protobuf:"varint,1,opt,name=has_order,json=hasOrder,proto3" json:"has_order,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasSuccessfulProductOrderResponse) Reset() {
	*x = HasSuccessfulProductOrderResponse{}
	mi := &file_v1_client_order_client_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSuccessfulProductOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSuccessfulProductOrderResponse) ProtoMessage() {}

func (x *HasSuccessfulProductOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_order_client_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSuccessfulProductOrderResponse.ProtoReflect.Descriptor instead.
func (*HasSuccessfulProductOrderResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_order_client_service_proto_rawDescGZIP(), []int{9}
}

func (x *HasSuccessfulProductOrderResponse) GetHasOrder() bool {
	if x != nil {
		return x.HasOrder
	}
	return false
}

func (x *HasSuccessfulProductOrderResponse) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

var File_v1_client_order_client_service_proto protoreflect.FileDescriptor

const file_v1_client_order_client_service_proto_rawDesc = "" +
	"\n" +
	"$v1/client/order_client_service.proto\x128github.com.martketplace.vkr.order.pkg.api.grpc.v1.client\x1a\x1cv1/domain/order_domain.proto\"\xdd\x02\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\x03R\n" +
	"productIds\x122\n" +
	"\x15expected_cart_version\x18\x04 \x01(\x04R\x13expectedCartVersion\x12^\n" +
	"\bdelivery\x18\x05 \x01(\v2B.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.DeliveryR\bdelivery\x12[\n" +
	"\apayment\x18\x06 \x01(\v2A.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.PaymentR\apayment\"k\n" +
	"\x10CheckoutResponse\x12W\n" +
	"\x06orders\x18\x01 \x03(\v2?.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderR\x06orders\"E\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"i\n" +
	"\x10GetOrderResponse\x12U\n" +
	"\x05order\x18\x01 \x01(\v2?.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderR\x05order\".\n" +
	"\x13GetOrderListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"o\n" +
	"\x14GetOrderListResponse\x12W\n" +
	"\x06orders\x18\x01 \x03(\v2?.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderR\x06orders\"H\n" +
	"\x12CancelOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"l\n" +
	"\x13CancelOrderResponse\x12U\n" +
	"\x05order\x18\x01 \x01(\v2?.github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.OrderR\x05order\"Z\n" +
	" HasSuccessfulProductOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"]\n" +
	"!HasSuccessfulProductOrderResponse\x12\x1b\n" +
	"\thas_order\x18\x01 \x01(\bR\bhasOrder\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId2\x91\a\n" +
	"\x12OrderClientService\x12\xa1\x01\n" +
	"\bCheckout\x12I.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutRequest\x1aJ.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutResponse\x12\xa1\x01\n" +
	"\bGetOrder\x12I.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderRequest\x1aJ.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderResponse\x12\xad\x01\n" +
	"\fGetOrderList\x12M.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListRequest\x1aN.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListResponse\x12\xab\x01\n" +
	"\fCancellOrder\x12L.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderRequest\x1aM.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderResponse\x12\xd4\x01\n" +
	"\x19HasSuccessfulProductOrder\x12Z.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderRequest\x1a[.github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderResponseBAZ?github.com/martketplace-vkr/order/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_order_client_service_proto_rawDescOnce sync.Once
	file_v1_client_order_client_service_proto_rawDescData []byte
)

func file_v1_client_order_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_order_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_order_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_order_client_service_proto_rawDesc), len(file_v1_client_order_client_service_proto_rawDesc)))
	})
	return file_v1_client_order_client_service_proto_rawDescData
}

var file_v1_client_order_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_client_order_client_service_proto_goTypes = []any{
	(*CheckoutRequest)(nil),                   // 0: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutRequest
	(*CheckoutResponse)(nil),                  // 1: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutResponse
	(*GetOrderRequest)(nil),                   // 2: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderRequest
	(*GetOrderResponse)(nil),                  // 3: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderResponse
	(*GetOrderListRequest)(nil),               // 4: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListRequest
	(*GetOrderListResponse)(nil),              // 5: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListResponse
	(*CancelOrderRequest)(nil),                // 6: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderRequest
	(*CancelOrderResponse)(nil),               // 7: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderResponse
	(*HasSuccessfulProductOrderRequest)(nil),  // 8: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderRequest
	(*HasSuccessfulProductOrderResponse)(nil), // 9: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderResponse
	(*domain.Delivery)(nil),                   // 10: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Delivery
	(*domain.Payment)(nil),                    // 11: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Payment
	(*domain.Order)(nil),                      // 12: github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
}
var file_v1_client_order_client_service_proto_depIdxs = []int32{
	10, // 0: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutRequest.delivery:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Delivery
	11, // 1: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutRequest.payment:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Payment
	12, // 2: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutResponse.orders:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
	12, // 3: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderResponse.order:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
	12, // 4: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListResponse.orders:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
	12, // 5: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderResponse.order:type_name -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order
	0,  // 6: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.Checkout:input_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutRequest
	2,  // 7: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.GetOrder:input_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderRequest
	4,  // 8: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.GetOrderList:input_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListRequest
	6,  // 9: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.CancellOrder:input_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderRequest
	8,  // 10: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.HasSuccessfulProductOrder:input_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderRequest
	1,  // 11: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.Checkout:output_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CheckoutResponse
	3,  // 12: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.GetOrder:output_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderResponse
	5,  // 13: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.GetOrderList:output_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.GetOrderListResponse
	7,  // 14: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.CancellOrder:output_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.CancelOrderResponse
	9,  // 15: github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.OrderClientService.HasSuccessfulProductOrder:output_type -> github.com.martketplace.vkr.order.pkg.api.grpc.v1.client.HasSuccessfulProductOrderResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_client_order_client_service_proto_init() }
func file_v1_client_order_client_service_proto_init() {
	if File_v1_client_order_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_order_client_service_proto_rawDesc), len(file_v1_client_order_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_order_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_order_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_order_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_order_client_service_proto = out.File
	file_v1_client_order_client_service_proto_goTypes = nil
	file_v1_client_order_client_service_proto_depIdxs = nil
}
