syntax = "proto3";

package github.com.martketplace.vkr.order.pkg.api.grpc.v1.client;

option go_package = "github.com/martketplace-vkr/order/pkg/api/grpc/v1/client;client";

import "v1/domain/order_domain.proto";

service OrderClientService {
  rpc Checkout(CheckoutRequest) returns (CheckoutResponse);
  rpc GetOrder(GetOrderRequest) returns (GetOrderResponse);
  rpc GetOrderList(GetOrderListRequest) returns (GetOrderListResponse);
  rpc CancellOrder(CancelOrderRequest) returns (CancelOrderResponse);
}

message CheckoutRequest {
  int64 user_id = 1;
  string checkout_id = 2;
  repeated int64 product_ids = 3;
  uint64 expected_cart_version = 4;
  .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Delivery delivery = 5;
  .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Payment payment =  6;
}

message CheckoutResponse {
  repeated .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order orders = 1;
}

message GetOrderRequest {
  int64 user_id = 1;
  int64 order_id = 2;
}

message GetOrderResponse {
  .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order order = 1;
}

message GetOrderListRequest {
  int64 user_id = 1;
}

message GetOrderListResponse {
  repeated .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order orders = 1;
}

message CancelOrderRequest {
  int64 user_id = 1;
  int64 order_id = 2;
}

message CancelOrderResponse {
  .github.com.martketplace.vkr.order.pkg.api.grpc.v1.domain.Order order = 1;
}
